### ISSUE TITLE
Support Capacitor 2?

### ISSUE THREAD

**Issue by CedNet** [capacitor-community/photoviewer#1]
I installed this into my app using capacitor 2 and got a build error saying "registerPlugin" was not found.

I just now saw you target Capacitor 3 beta. 

Any plan to support current Capacitor version? I really need this plugin...

**Comment by jepiqueau** [comment]
@CedNet First thanks for looking at the plugin. The plugin has been fully written for Capacitor3 which will come soon. So i did not plan any release for Capacitor 2. May be it will be better to look at moving your app to Capacitor 3 which anyhow you will have to do in a near future. Sorry for this

**Comment by CedNet** [comment]
I can wait then :-) hopefully Capacitor 3 has a release candidate soon.

I'll close this issue so it's not in your way.

**Comment by jepiqueau** [comment]
@CedNet Capacitor 3 is on release candidate 0 now
