### ISSUE TITLE
React code example

### ISSUE THREAD

**Issue by blatoo** [capacitor-community/photoviewer#10]
Hi @jepiqueau ,

can you give a small example about how to use it in react? I only know react.... 😅

Thousand thanks!!! 🌷
Conny

**Comment by jepiqueau** [comment]
@blatoo Is this for web or for native ? and do you use Ionic/React?

**Comment by blatoo** [comment]
@jepiqueau it is for native. And I am only use Ionic/React... 😄

**Comment by jepiqueau** [comment]
@blatoo i am working on a vite react basic example which works well for native but requires some modifications of the jeep-photoviewer stencil component to work better. I will post this app as is this should help you to start with Ionic/React app.

**Comment by jepiqueau** [comment]
@blatoo look at [vite-react-photoviewer-app](https://github.com/jepiqueau/vite-react-photoviewer-app)

**Comment by blatoo** [comment]
Hi @jepiqueau you are awesome!!! Thousand thanks!!! 🌹 🌹 🌹
