### ISSUE TITLE
Add an option to open slider directly

### ISSUE THREAD

**Issue by sverdlov** [capacitor-community/photoviewer#11]
It will be nice to have possibility to open image slider directly, without opening image gallery.
It can be two options like `skipGallery: boolean` and `startFrom: number`. Where `startFrom` is index of image those must be opened. Also return in [capShowResult](https://github.com/capacitor-community/photoviewer/blob/main/docs/API.md#capshowresult) index of current image when viewer was closed.

For example same functionality in another app. Pay attention viewer starts from third image, and after closing viewer active image on slider also changed.
![doc_2022-01-12_15-17-52](https://user-images.githubusercontent.com/15052094/149148070-9b495d5d-ccc9-4e96-8b76-48d174cb578a.gif)

**Comment by jepiqueau** [comment]
@sverdlov thanks for using the plugin. i will implement this new feature. I did it yesterday in the `jeep-photoviewer` Stencil component which is used in the `@capacitor-community/photoviewer` i will now concentrate on the plugin itself. Can you try the Stencil component and tell me if it is what you want.

**Comment by jepiqueau** [comment]
@sverdlov This has been added to release 1.0.8 Enjoy it

**Comment by jepiqueau** [comment]
@sverdlov i close the issue feel free to re-open it if necessary

**Comment by sverdlov** [comment]
[jepiqueau](https://github.com/jepiqueau) Sorry, didn't see notification. Thank you for work. I'll try it as soon as possible

**Comment by sverdlov** [comment]
@jepiqueau I've check it. Nice work, thanx)
