### ISSUE TITLE
 Error: "PhotoViewer" plugin is not implemented on android Error: "PhotoViewer" plugin is not implemented on android

### ISSUE THREAD

**Issue by krunalsk007** [capacitor-community/photoviewer#12]
**Describe the bug**
 Error: "PhotoViewer" plugin is not implemented on android Error: "PhotoViewer" plugin is not implemented on android

**To Reproduce**
install the plugin and then click on the image at that time I am getting this error.
(i follow all the instructions)

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by jepiqueau** [comment]
@krunalsk007 can you share your Package.json file and the project and app gradle files

**Comment by krunalsk007** [comment]
after uninstall and install and following all instruction  i am not getting this error  and sorry i am uninstalled this plugin because  i am facing two issue on it 
 1. my some image was png and its in black color so its is not display on screen.
 2. and i cant able to share image when i am  try to share images then it will show me toast for image created and then it was show me toast that failed with path of image (like data/data/... ).

**Comment by jepiqueau** [comment]
@krunalsk007 Hi, i did not reply quickly as i was busy with 2 of my others plugins but i am able to improve the plugin if a feature is missing or if there are bugs. 
1. Can you share one of your png or give me a link to a similar png so i can make a fix for this.
2. check your AndroidManifest.xml file it should contains 
```
        <provider
            android:name="androidx.core.content.FileProvider"
            android:authorities="${applicationId}.fileprovider"
            android:exported="false"
            android:grantUriPermissions="true">
            <meta-data
                android:name="android.support.FILE_PROVIDER_PATHS"
                android:resource="@xml/file_paths"></meta-data>
        </provider>
```
take care of `android:authorities="${applicationId}.fileprovider"` it was on earlier version `android:authorities="${applicationId}.provider"`

**Comment by jepiqueau** [comment]
@krunalsk007 the `backgroundcolor` parameter  has been added so png black images can now be displayed.
'backgroundcolor' can be in  `["white", "ivory", "lightgrey", "darkgrey", "grey", "dimgrey", "black"]` default is `"black"` 
hope this help you to change your mind and use the plugin. Anyhow it helps me to solve an issue
