### ISSUE TITLE
Could not find com.github.MikeOrtiz:TouchImageView:3.1.1.

### ISSUE THREAD

**Issue by dyegonery** [capacitor-community/photoviewer#13]
**Describe the bug**
This plugin is having problems with its dependencies, specifically with com.github.MikeOrtiz:TouchImageView:3.1.1

**To Reproduce**

1. ionic capacitor run android

**Expected behavior**
Run ionic app on simulator using Capacitor 3.4.1

**Screenshots**
![Screenshot from 2022-02-11 11-36-59](https://user-images.githubusercontent.com/4934602/153611147-c7f31951-6923-4f13-9b18-43f08027bdb4.png)

**Capacitor:**
 - Capacitor CLI: 3.4.1
 - @capacitor/android: 3.4.1
 - @capacitor/core: 3.4.1
 -

**Comment by meriturva** [comment]
You have to add repository on your build.gradle file:

`maven { url 'https://jitpack.io' }`

see on readme or on android example project: https://github.com/jepiqueau/angular-photoviewer-app

**Comment by jepiqueau** [comment]
@meriturva thanks for giving the answer.
@dyegonery if it works now on your side can you close the issue

**Comment by jepiqueau** [comment]
@dyegonery I assume this is solve so i close the issue
