### ISSUE TITLE
iOs status-bar glitch

### ISSUE THREAD

**Issue by ivanov84** [capacitor-community/photoviewer#17]
**Is your feature request related to a problem? Please describe.**
When ios app uses visible status-bar then when image is opened in photoiewer then status-bar starts becaming hidden and when I got back - status-bar appeared again but my ionic app is getting up and down. It's very annoying.

I modifyed code in OneImageViewController.swift file:
```
override var prefersStatusBarHidden: Bool {
  //return true
  return false
}
```

it's better but in this case images are rendered behind status-bar with transcluent background - it's visually like some kind of bug.

**Describe the solution you'd like**
option to hide status-bar or not with image rendering below of status-bar.

**Comment by jepiqueau** [comment]
@ivanov84 have you had a look to [angular-photoviewer-app](https://github.com/jepiqueau/angular-photoviewer-app). Do you have that issue. Could you share a repro app with the issue so i can look at it

**Comment by jepiqueau** [comment]
@ivanov84 Did you find a solution for this?

**Comment by ivanov84** [comment]
@jepiqueau I used code that mentioned above. It's not very nice, but it's ok.
