### ISSUE TITLE
Ability to open local image in photoViewer

### ISSUE THREAD

**Issue by ivanov84** [capacitor-community/photoviewer#18]
I'm developing app that store images locally and after saving it with Capacitor I have url like this:
http://localhost/_capacitor_file_/data/user/0/com.xxx.xxx.android/files/custom-event-16589244521170.png

That kind of url is not opened by viewer. It could be very usefull if plugin could do it.

**Comment by ivanov84** [comment]
file:///data/user/0/com.xxx.xxx.android/files/love-event-16589258525491.png works. Sorry.

**Comment by jepiqueau** [comment]
@ivanov84 thanks for using the plugin
