### ISSUE TITLE
Open a fullscreen view with the path of image ( url or local )

### ISSUE THREAD

**Issue by amanngoel** [capacitor-community/photoviewer#2]
**Describe the solution you'd like**
A function , showFullScreenImage(path) , which makes the image appear on the acreen using path, not by any grid selection.

**Describe alternatives you've considered**
https://www.npmjs.com/package/com-sarriaroman-photoviewer

**Comment by jepiqueau** [comment]
@amanngoel thank you for using the plug-in. I am in vacation right now. I will have a look when I am back and complete the migration to capacitor 3 of my other plug-ins.

**Comment by stewones** [comment]
installed everything to only then realizing this is not for me. given the plugin name I thought it was some kind of individual media viewer

**Comment by jepiqueau** [comment]
@stewones thanks for trying to use the plugin. Can you explain what you where looking for. Is it the same that @amanngoel  ask for only a showFullScreenImage(path). `path` being a url or a link to an individual image in the device. Can you confirm so i will have a look to add this functionality

**Comment by jepiqueau** [comment]
@stewones @amanngoel  in fact the solution i will go for this  if you provide only one image url you will see the image and can go fullscreen and have the pan and zoom facilities, and if you provide a set of urls you will see the gallery. Will that suit your need

**Comment by stewones** [comment]
@jepiqueau hey hey. Yeah exactly, I think that would work.

I need a way to just tap a small img in the view and open some kind of modal or something to be zooming it.

**Comment by jepiqueau** [comment]
@amanngoel @stewones it has been fixed for Web and iOS platforms in release 0.0.3. Can you have a look to see if it suit your needs. I will concentrate on Android platform now

**Comment by stewones** [comment]
Awesome thank you. I'll try tomorrow 👍

**Comment by stewones** [comment]
@jepiqueau love it, tested iOS and that's exactly what I'm looking for.
the only issue is that I'm not able to close the modal once it's open?
<img src="https://user-images.githubusercontent.com/719763/134073347-8d90cf4d-8976-4051-a7cc-f05ad43df7a2.jpeg" width="350">

**Comment by stewones** [comment]
another thing I just noticed is that once it's loaded I need to do a first tap on the picture to be able to zoom and drag around.

**Comment by stewones** [comment]
got this error if I set `title:false` and no `title` inside the `images` object

```
Thread 1: "the cell returned from -collectionView:cellForItemAtIndexPath: does not have a reuseIdentifier - cells must be retrieved by calling -dequeueReusableCellWithReuseIdentifier:forIndexPath:"
```

![Screen Shot 2021-09-20 at 18 16 00](https://user-images.githubusercontent.com/719763/134076831-810dfd71-8174-4cb3-86ea-f5a32b7f8f79.png)

**Comment by jepiqueau** [comment]
@stewones Thanks for testing and having all this comments back.
- i suppress the close button as otherwise it will go back to the gallery which is not what you want so where do you want to go as there is no page before? and i assume you do not want to close the app Tell me
- yes you need a first tap on the picture to hide the button and a double tap to be able to zoom in/out or pan I may have a look if i can make directly a double tap which will hide automatically automatically the button when opening the zoom but i am not sure i can do it
- i forgot to test the `title:fase` so i will have a look

**Comment by jepiqueau** [comment]
@stewones it is not the `title:false` which create the effect as in fact this has no effect but it is the fact that you do enter title in the image object so i will have a look

**Comment by jepiqueau** [comment]
@stewones all the above issues have been fixed in release 0.0.5 for iOS only. it will come later for Web and Android

**Comment by jepiqueau** [comment]
@stewones forgot to mentioned that you have now two gestures
- tap (old behavior)
- double tap  go to the zoom-in straightforward

**Comment by stewones** [comment]
I don't know if it's intentional but from my own experience users won't know they need to do a first tap to be able to zoom around. once they figure this out they won't know how to close the modal because the X button goes away while zooming and they need to do another tap again to have it back.

is that hard to

- make X button always visible no matter what
- enable zoom right after modal opens (without the need of tapping first)

**Comment by stewones** [comment]
honestly I don't care about the title at all and think users won't care too, but those 2 points I listed would be super important.

**Comment by jepiqueau** [comment]
@stewones i kept the tap for maintaining the old behavior, but you can use the double tap to open directly the zoom view as we need a point to zoom around. To zoom i use a third party software which is not allowing a close button this is why you need to tap to get back to my own image view where i managed the close button. It is simple like this. So it will be difficult to do what you said without re-writting the plugin from scratch and develop my own image view with touch gesture capabilities. I did it easily for iOS but i am struggling for more than two days without success yet in Android. So their is a limit to one's can ask for.

**Comment by jepiqueau** [comment]
@stewones Not being able yet to find the solution for android i come back on your two points. 
I assume this two points are valid for the `one image` mode not for the `gallery` mode.
When you say `enable zoom right after modal opens (without the need of tapping first)`  
Did you mean that you present the image already zoomed at the `maxzoomscale` around the `center point`?
To day what i am doing is presenting the image fullscreen with no zoom and you double tap on point and the image is zoomed around that point at the `maxzoomscale`.
Can you precise a bit more your thoughts on that point

**Comment by stewones** [comment]
@jepiqueau yeah I never even tested gallery mode yet. 

Look at Instagram, when you scroll down your feed, you just zoom the image. There's no need of extra taps in order to do that. You put your two fingers on top of it and make the movement from inside out, that's it 😛

**Comment by jepiqueau** [comment]
@stewones so what your are looking for is not a zoom it is a pinch of the image with your two fingers. Is that true ?  So this will require to write a special code for one image with no impact on the gallery mode.

**Comment by stewones** [comment]
Pinch to zoom yeah

Another example

https://pinch-zoom-element.glitch.me

**Comment by jepiqueau** [comment]
@stewones I have implemented the one image pinch-zoom & pan for iOS and Android as i thought you would like to have in release 1.0.0. Can you tell if it is what you want to get and confirm that it works well in iOS (i only test with a simulator). I tested it in Android both with emulator and physical device.
@amanngoel Is this implementation fit your initial request?

**Comment by jepiqueau** [comment]
@stewones @amanngoel as no one answered, I will close the issue f

**Comment by jepiqueau** [comment]
@stewones @amanngoel feel free to re-open it if necessary

**Comment by stewones** [comment]
Hey hey bro , sorry for not replying quickly, going through many things right now. I'll try again asap and get back with my feedback.

**Comment by jepiqueau** [comment]
@stewones 👍
