### ISSUE TITLE
Photoviewer for Capacitor 4?

### ISSUE THREAD

**Issue by Th-Barth** [capacitor-community/photoviewer#20]
Hi, is there a chance to get this Photoviewer for Capacitor 4 as well? I tried to install this photoviewer, but I get a dependency error:

npm install @capacitor-community/photoviewer
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: echat-app@0.0.1
npm ERR! Found: @capacitor/core@4.1.0
npm ERR! node_modules/@capacitor/core
npm ERR!   @capacitor/core@"^4.0.1" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer @capacitor/core@"^3.4.1" from @capacitor-community/photoviewer@1.1.3
npm ERR! node_modules/@capacitor-community/photoviewer
npm ERR!   @capacitor-community/photoviewer@"*" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.

**Comment by jepiqueau** [comment]
@Th-Barth This is done in @capacitor-community/photoviewer@2.0.1 so i close the issue
