### ISSUE TITLE
Doesn't show from webPath

### ISSUE THREAD

**Issue by Elardzhi** [capacitor-community/photoviewer#22]
Why does it not show images from local webPaths like `capacitor://localhost/_capacitor_file_/...`?

**Comment by jepiqueau** [comment]
@Elardzhi i am working for images in the DCIM folder which folder do you want to adress on iOS and on Android

**Comment by Elardzhi** [comment]
@jepiqueau this webPath `capacitor://localhost/_capacitor_file_/....` is returned by Capacitor/Camera. On Android, it should be ` http://localhost/......`
It would be great if this photoviewer showed images from those webPaths.

**Comment by Elardzhi** [comment]
@jepiqueau 
It opens from `file://` it doesn't open from `capacitor://`

**Comment by jepiqueau** [comment]
@Elardzhi yes from file: i do not know about capacitor://

**Comment by ivanov84** [comment]
@Elardzhi if you want to open an image on android then use code:
`this._src = Capacitor.convertFileSrc(data.uri);`

**Comment by jepiqueau** [comment]
@Elardzhi Can you give the full path of image returns by the capacitor/camera plugin

**Comment by Elardzhi** [comment]
I found this closed issue: #18 
So I can update local webPaths the same way.

**Comment by jepiqueau** [comment]
@Elardzhi fix in 2.04
