### ISSUE TITLE
Gradle 7

### ISSUE THREAD

**Issue by Elardzhi** [capacitor-community/photoviewer#23]
This plugin doesn't work with Gradle 7.
This is the error: 
```org.gradle.internal.metaobject.AbstractDynamicObject$CustomMessageMissingMethodException: Could not find method compile() for arguments [com.commit451:PhotoView:1.2.4] on object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.```

**Comment by jepiqueau** [comment]
@Elardzhi look at https://github.com/jepiqueau/angular-photoviewer-app. It works with gradle 7

**Comment by Elardzhi** [comment]
Sorry, that error was caused by another photoviewer
