### ISSUE TITLE
dataUrl is not working 

### ISSUE THREAD

**Issue by Elardzhi** [capacitor-community/photoviewer#24]
Showing images using dataUrl (base64 string) is not working in versions 2.0.3 and 2.0.2.
Had to downgrade to 2.0.1 where it works fine.

**Comment by jepiqueau** [comment]
@Elardzhi Can you provide me an http link to a base64 image, I never test base64 images and it is not mentioned anywhere in the doc that you can use them so it is pretty interesting that these images were displayed in 2.0.1

**Comment by Elardzhi** [comment]
Your readme.md says: "A picture can be acessed by image web url, base64 data or from internal device for iOS and Android."

And your demo app `vite-react-photoviewer-app` has `base64Images` example

**Comment by jepiqueau** [comment]
@Elardzhi you right i forgot about this it will be back on the next release as well as urls starting with capacitor://localhost/_capacitor_file_/. This as required much more work on the code that forseen. Sorry for the disturbance in your work.

**Comment by jepiqueau** [comment]
@Elardzhi fix in 2.04
