### ISSUE TITLE
Close Viewer in Android

### ISSUE THREAD

**Issue by Elardzhi** [capacitor-community/photoviewer#25]
When I close the viewer on Android it closes the whole app. 
Tested on emulator only for now.

https://user-images.githubusercontent.com/6604025/193420044-186f7c5a-5c27-46ae-86ec-ebc96518b18f.mov

**Comment by Elardzhi** [comment]
this is
![Screen Shot 2022-10-01 at 1 19 50 PM](https://user-images.githubusercontent.com/6604025/193421008-9f3f30a3-79cb-4ad7-9e27-00fab7844ee6.png)
 the error:

**Comment by Elardzhi** [comment]
I used the same component and the hook from `vite-react-photoviewer-app` and they didn't work with Ionic for some reason.
Using PhotoViewer.show() directly works fine.

**Comment by Sampath-Lokuge** [comment]
I have the same issue with the Ionic/Angular app. Can you tell me how have you fixed this? Thanks!

**Comment by Elardzhi** [comment]
Do you use their demo app?
