### ISSUE TITLE
The close button is not visible in iOS with Light theme on

### ISSUE THREAD

**Issue by bozhidarc** [capacitor-community/photoviewer#27]
**Describe the bug**
When an image is open in "slider" mode in iOS with Light theme on, the close button is not visible. 
The button is there but it blends with the background.
If I tap the image the background changes to black, but the button disappears.

**To Reproduce**
1. Open an image in slider mode.
2. Observe the close button.

**Expected behavior**
The close button color to depend on the iOS theme.

**Screenshots**
![image](https://user-images.githubusercontent.com/323252/199970460-d51a36fc-cf50-481a-b9e5-42314375be61.png)

**Desktop (please complete the following information):**
 - OS: iOS 16
 - Ionic 6
 - Capacitor 4

**Smartphone (please complete the following information):**
 - Device: iPhone 13 Pro
 - OS: 16

**Comment by jepiqueau** [comment]
@bozhidarc thanks for reporting this. If you want to make a PR for this feel free. I am away for the next 3 weeks.

**Comment by bozhidarc** [comment]
I made a PR, it also fixes the share button.

**Comment by jepiqueau** [comment]
@bozhidarc can you also add you in the contributor list in the readme  and add one to the contributor number. When rhis is done i will merge the 2 PR's but i will not be in a position to publish it on npm before i am back home

**Comment by jepiqueau** [comment]
@bozhidarc your PR has been merged and part of release 2.0.6. So i close the issue
