### ISSUE TITLE
Close/share buttons don't show when in light mode on iOS

### ISSUE THREAD

**Issue by jjgriff93** [capacitor-community/photoviewer#29]
**Describe the bug**
The buttons are black on a black background when in light mode on iOS, making them invisible. 

**Expected behavior**
Depending on the background colour, the buttons should be an inverse colour so they're visible.

**Smartphone (please complete the following information):**
 - Device: iPhone 14
 - OS: iOS 16.1

**Additional context**
Using the latest version of this plug-in (1.0.8)

**Comment by jepiqueau** [comment]
@jjgriff93 this has been fixed in 2.08 see #27
Update to that release

**Comment by jepiqueau** [comment]
@jjgriff93  No news from you i assume you tried 2.0.8 so i close the issue
