### ISSUE TITLE
Preview need

### ISSUE THREAD

**Issue by Lyfei** [capacitor-community/photoviewer#33]
It is recommended to include some previews in the README

**Comment by jepiqueau** [comment]
@Lyfei feel free to make a PR with some previews  of the different modes i will merge it

**Comment by shiv19** [comment]
@Lyfei 

https://github.com/capacitor-community/photoviewer/assets/9407019/ed1687e8-8e23-4bb0-9c3a-08973a03e8e8

**Comment by robingenz** [comment]
I am closing this issue as it is no longer active. Feel free to create a PR.
