### ISSUE TITLE
ios invisible close button when opens images list in a slider mode

### ISSUE THREAD

**Issue by ivanov84** [capacitor-community/photoviewer#36]
**Describe the bug**
when user opens images list in a slider mode - close button is not visible because it's white. But when press on image to zoom mode and then press again to get back - you can see close button for 1 second and can press on it.

**To Reproduce**
Open on ios images array in slides mode.
`const capImages: Array<Image> = ['image1.jpg','image2.jpg','image3.jpg'];`
`const viewerOptions: ViewerOptions = {share: true, title: false};`
`const capOptions: capShowOptions = {images: capImages, mode: 'slider', startFrom: targetIndex, options: viewerOptions};`
`try {`
`  await PhotoViewer.show(capOptions);`
`}`
`catch (e) {`
`  console.error(`Unable open image in photoviewer`, e);`
`}`

**Expected behavior**
black background or black close button or grey box under close button.

**Screenshots**
![image](https://user-images.githubusercontent.com/9296077/225401481-a2991612-706b-4b21-bf3a-8c1a99cb6ea0.png)
![image](https://user-images.githubusercontent.com/9296077/225401498-ac030ca8-beac-4009-a76b-e57fb6a64281.png)
![image](https://user-images.githubusercontent.com/9296077/225401506-71cd77c4-33a0-4d2e-8874-98bc47d42b5f.png)

**Desktop (please complete the following information):**
 - OS: iOS
 - Capacitorjs 4.1.0

**Comment by jepiqueau** [comment]
@ivanov84 Which release of the plugin are you using? Have you tried with `@capacitor-community/photoviewer@2.0.10`

**Comment by ivanov84** [comment]
@jepiqueau I will try next release and reply here.

**Comment by ivanov84** [comment]
@jepiqueau same problem with new version 2.0.9 on ios.

The close button is invisible again when the one image is opened:

![2023-05-11_14-44-54](https://github.com/capacitor-community/photoviewer/assets/9296077/2c7f0ea0-7a08-447b-b3aa-020e3843c0e9)

Also some images in the new version are not loading correctly, I think because of the new version of native ios links. I downgraded to version 2.0.1 and it worked but with a hidden close button like in the new version:

![2023-05-11_15-02-54](https://github.com/capacitor-community/photoviewer/assets/9296077/8157cb7c-b2b1-4838-9627-0aaafa61aaa5)

**Comment by ivanov84** [comment]
@jepiqueau IMHO it could be ideal to realise this concept:

background color when opens image but when 1 click then - title hides - click again - show, double tap - zoom

![IMG_5077](https://github.com/capacitor-community/photoviewer/assets/9296077/bc2caa73-6dd1-4083-971b-63457abf4f34)
![IMG_5078](https://github.com/capacitor-community/photoviewer/assets/9296077/a6bd8ed1-d910-44ac-b297-c475dcf147ae)
![IMG_5079](https://github.com/capacitor-community/photoviewer/assets/9296077/c04e6938-38db-48de-a411-e997394038ce)

**Comment by jepiqueau** [comment]
@ivanov84 this has been fixed in 2.1.0 & 3.0.0-beta.1 releases
