### ISSUE TITLE
Image title on Android

### ISSUE THREAD

**Issue by Elardzhi** [capacitor-community/photoviewer#39]
The image title is optional in the docs. But Android throws an error and doesn't open a modal if it is missing.

**Comment by jepiqueau** [comment]
@Elardzhi have you set 
```
this.options.title = false
```

**Comment by jepiqueau** [comment]
@Elardzhi this will be fixed in 3.0.3

**Comment by jepiqueau** [comment]
@Elardzhi i assume it is fixed now so i close the issue
