### ISSUE TITLE
Error: "PhotoViewer.normalize()" And "PhotoViewer.process()" is not implemented on ios/Android

### ISSUE THREAD

**Issue by farshidpg** [capacitor-community/photoviewer#40]
Hi, After install and config plugin successfully in android and ios I can't see anything in my  app  ( vue example demo )

in both platfroms ( iOS/Android ) I get these 2 error in console :

ios :
[Error] Unhandled Promise Rejection: Error: "PhotoViewer.normalize()" is not implemented on ios
[Error] Unhandled Promise Rejection: Error: "PhotoViewer.process()" is not implemented on ios
Android :
[Error] Unhandled Promise Rejection: Error: "PhotoViewer.normalize()" is not implemented on android
[Error] Unhandled Promise Rejection: Error: "PhotoViewer.process()" is not implemented on android

I using the 

"ionic vue" : "7.0.3"
"capacitor" : "4.7.3"
"capacitor-community/photoviewer": "2.0.10",

Also I done the installation steps and there no any error in build process and run commands :

ionic capacitor sync
ionic capacitor update
ionic capacitor copy
....

but the errors still in iOS/Android

**Comment by jepiqueau** [comment]
@farshidpg Was it working in previous releases like Ionic 6?

**Comment by jepiqueau** [comment]
@farshidpg the plugin got only two methods 
echo and show so i do not know about normalize and process methods.
As i am away travelling for the next three weeks can you try downgrading to ionic 6 and capacitor 4.6.x

**Comment by jepiqueau** [comment]
@farshidpg No feedback so i assume it is fixed so i close the issue. Feel free to re-open it if require
