### ISSUE TITLE
iOS Share & Close button not visible

### ISSUE THREAD

**Issue by anthonyplews** [capacitor-community/photoviewer#42]
**Describe the bug**
When opening a single image with the Photoviewer the share and close button are not visible:

**Code:**

`PhotoViewer.show({ images: [{ url: this.user.media.url, title: '' }], mode: 'one', options: { title: false, compressionquality: 1 } });`

I'm still able to guess where the buttons are and they are functional when tapped.

**Environment:**

Ionic Capacitor 5

![IMG_16DCEBCE953B-1](https://github.com/capacitor-community/photoviewer/assets/38831066/e1273c10-e9e1-4636-aab2-872494a371fc)

**Comment by anthonyplews** [comment]
@jepiqueau no I didn't specify a color:

`PhotoViewer.show({ images: [{ url: this.user.media.url, title: '' }], mode: 'one', options: { title: false, compressionquality: 1 } });`

**Comment by anthonyplews** [comment]
Figured out what is causing the issue... it has to do with the light or dark mode settings in iOS, take a look at the recording below:

https://github.com/capacitor-community/photoviewer/assets/38831066/5c98a788-fe33-4f43-a032-beb9c46d6de3

**Comment by jepiqueau** [comment]
@anthonyplews thanks for this i will have a look

**Comment by jepiqueau** [comment]
@anthonyplews this has been fixed in 2.1.0 & 3.0.0-beta.1 releases

**Comment by anthonyplews** [comment]
Thank you will test tomorrow!

**Comment by anthonyplews** [comment]
Works! Thank you @jepiqueau
