### ISSUE TITLE
Close Bar appears when before an image is selected when Gallery View is used

### ISSUE THREAD

**Issue by vicatcu** [capacitor-community/photoviewer#44]
**Describe the bug**
For some reason the class="photobuttons-container" div always seems to appears while in the gallery view, and clicking the close button makes the gallery disappear. I don't know what use-case this supports or if it's intentional, but I don't want that in my application. How can I change it?

**To Reproduce**
This behavior / bug is evident without modification when you launch the example app at https://github.com/jepiqueau/angular-photoviewer-app, open it in a web browser, and click on Mode Gallery.

**Expected behavior**
When the Gallery Mode is selected, the Close Bar should not be displayed while the gallery is being displayed rather than one of the photos being selected.

**Screenshots**

![image](https://github.com/capacitor-community/photoviewer/assets/1018382/9d00321b-1746-4fae-9308-3fc55303e7d2)

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Browser Chrome
 - Version 114.0.5735.198 (Official Build) (64-bit)

**Comment by jepiqueau** [comment]
@vicatcu Thanks for your comment, the use case is when your application is multi-pages or the gallery is set in a modal window you need this button to go back to the previous page or to close the modal
