### ISSUE TITLE
Output Events

### ISSUE THREAD

**Issue by vicatcu** [capacitor-community/photoviewer#45]
**Describe the solution you'd like**
My application requires a user to optionally check a box associated with each image in the gallery. Right now, I don't see any way to selectively style the gallery (e.g. by mutating the images input somehow), and I don't have any events to tell me when an image has been selected from the gallery, or when full screen mode has been closed and the gallery is again visible. I need some combination of these behaviors to achieve my desired user experience. I also don't have an idea of how I might overlay my own user interface elements onto the gallery view.

**Describe alternatives you've considered**
Two ways I could accomplish this are:
1. Put an overlay on top of the gallery with positioned checkboxes above the images (e.g. in the lower right corner of them), or
2. When an image is selected in full screen mode, display a checkbox that the user can interact with, and when in gallery mode 'highlight' (e.g. with a thick border, or otherwise) those images that are 'checked'

**Comment by jepiqueau** [comment]
@vicatcu This is something quite specific for your application. it is not plan to do this
