### ISSUE TITLE
Create tags for 3.0.2 and 3.0.3

### ISSUE THREAD

**Issue by chiraganand** [capacitor-community/photoviewer#53]

**Comment by jepiqueau** [comment]
@chiraganand i do not know what do you mean be more explicit

**Comment by chiraganand** [comment]
These version tags are missing from the git tags list. Since you created these versions in package.json it would be good that they also exist as git tags.

**Comment by jepiqueau** [comment]
@chiraganand yes sorry about this i just forgot

**Comment by jepiqueau** [comment]
@chiraganand i checked they are v3.0.3 and v3.0.2 there are automatically created when i publish with npx np

**Comment by chiraganand** [comment]
Ah yes, they do exist! Just checked that my fork is missing these tags.
