### ISSUE TITLE
Upgrade from Capacitor 5 to Capacitor 6

### ISSUE THREAD

**Issue by LammbdA** [capacitor-community/photoviewer#62]
**Objective**
Upgrade the @capacitor-community/photoviewer plugin from Capacitor 5 to Capacitor 6.

**Comment by connysvensson** [comment]
This branch (https://github.com/dootixsa/photoviewer) seems to have done the work, can someone just merge this back here?

**Comment by robingenz** [comment]
Done, see https://github.com/capacitor-community/photoviewer/releases/tag/v4.0.0
