### ISSUE TITLE
bug: base64 string no longer work with the show function on Android

### ISSUE THREAD

**Issue by tiennp-dev** [capacitor-community/photoviewer#68]
**Plugin version:** On the latest version 4.0.0

**Platform(s):** Android

**Current behavior:**
I am using the show function of the Photoviewer plugin in my Ionic app with a Base64 string (e.g., "data:image/jpeg;base64,/9j/4AAQSkZJ.....TY3OD=="). However, this results in an error:

![image](https://github.com/user-attachments/assets/1a9f87a8-8571-4a37-9dea-6e7f79c6b282)
![image](https://github.com/user-attachments/assets/58fa0ed8-a549-4624-9f26-ecd030129b68)

I've been able to resolve this issue in 'one' mode but, due to my limited experience with Java, I haven't been able to create a PR to address the issue fully. Please refer to the `Related Code` section for more details.

**Expected behavior:** The plugin should support Base64 strings as described in the README.

**Steps to reproduce:** N/A

**Related code:**
Here is my usage in my Ionic app, which very simple
```
      if (Capacitor.isNativePlatform()) {
        await PhotoViewer.show({
          images: [
            { url: base64string, title: (new Date()).getTime().toString() }
          ],
          options: {
            compressionquality: 0.8,
            share: true,
          },
          mode: 'one',
          startFrom: 0
        })
        return;
      }
```

The issue seems to be related to this file: [ImageFragment.kt](https://github.com/capacitor-community/photoviewer/blob/main/android/src/main/java/com/getcapacitor/community/media/photoviewer/fragments/ImageFragment.kt). Below is a snippet of the code where the issue occurs:

```
        val mImageToBeLoaded = ImageToBeLoaded()
        val toBeLoaded = image.url?.let { mImageToBeLoaded.getToBeLoaded(it) }

        if (toBeLoaded is String) {
            // load image from url
            val lazyHeaders = LazyHeaders.Builder()
            for (key in customHeaders.keys()) {
                customHeaders.getString(key)?.let { lazyHeaders.addHeader(key, it) }
            }
            val glideUrl = GlideUrl(toBeLoaded, lazyHeaders.build())
            GlideApp.with(appContext)
                .asBitmap()
                .load(glideUrl)
                .fitCenter()
                .diskCacheStrategy(DiskCacheStrategy.ALL)
                .into(ivTouchImage)
        }
```

In cases when `toBeLoaded` returns a Base64 string, the current implementation doesn't handle it properly. 
I added the following check to address this, and it worked as expected. 
I believe this issue is related to [this commit](https://github.com/capacitor-community/photoviewer/commit/431e12d90313f42c8a0a7d9fdedb19db064cd560#diff-a072f4916b8e7bd91109dd52da35ae58772f7858800a6382c503fed8d591184f), which introduced support for custom headers but didn't account for Base64 strings.

```
        if (toBeLoaded is String) {
            if (toBeLoaded.contains("base64")) {
                GlideApp.with(appContext)
                    .asBitmap()
                    .load(toBeLoaded)
                    .fitCenter()
                    .diskCacheStrategy(DiskCacheStrategy.ALL)
                    .into(ivTouchImage)
            }
            else {
                // load image from url
                val lazyHeaders = LazyHeaders.Builder()
                for (key in customHeaders.keys()) {
                    customHeaders.getString(key)?.let { lazyHeaders.addHeader(key, it) }
                }
                val glideUrl = GlideUrl(toBeLoaded, lazyHeaders.build())
                GlideApp.with(appContext)
                    .asBitmap()
                    .load(glideUrl)
                    .fitCenter()
                    .diskCacheStrategy(DiskCacheStrategy.ALL)
                    .into(ivTouchImage)
            }
        }
```

**Other information:** This is my first time creating an issue, so please feel free to correct me if I’ve made any mistakes.

**Comment by robingenz** [comment]
@shiv19 Could you take a look at this?

**Comment by shiv19** [comment]
@robingenz, I will submit a fix for this today.
@tiennp-dev, thanks for reporting this issue!

**Comment by tiennpdev** [comment]
@shiv19 Thank you for your prompt improvements!!
