### ISSUE TITLE
Wrong image ratio / Image cut off

### ISSUE THREAD

**Issue by mariusbolik** [capacitor-community/photoviewer#7]
**Describe the bug**
The image is displayed in the ratio 1:1 if opened the first time. If I open the photo viewer again, the image is displayed correctly. See the video for more details.

**Expected behavior**
The picture shouldn't be cut off.

**Screenshots**
<video src="https://user-images.githubusercontent.com/39862171/145538451-e18ef515-87a1-4757-a2ba-6963a719e004.mp4"></video>

**Smartphone (please complete the following information):**
 - Device: iPhone 11 mini
 - OS: 15

**Comment by jepiqueau** [comment]
@mariusbolik Well strange behavior i will have a look

**Comment by jepiqueau** [comment]
@mariusbolik Can you share the code or a small repro app on github

**Comment by jepiqueau** [comment]
@mariusbolik this is fixed in 1.0.3. Feel free to close the issue when tested on your side

**Comment by mariusbolik** [comment]
@jepiqueau works perfectly! Thank you for the fast help!
