### ISSUE TITLE
Manually close the image

### ISSUE THREAD

**Issue by wrurik** [capacitor-community/photoviewer#8]
Thanks for this plugin.

Is it possible to manually close the image view?
I would like to close it when Android backbutton is pressed.

**Comment by jepiqueau** [comment]
@wrurik this is fixed in version 1.0.4

**Comment by wrurik** [comment]
Just tested it in my project and seems to be working.

Thank you!

**Comment by jepiqueau** [comment]
@wrurik 👍i close the issue
